name: 'Monthly Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update
        run: |
          echo "one month" >> monthly.log
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git status
          git add monthly.log
          git commit -m "Monthly update"
          git log
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
